version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: feedzy_mysql
    volumes:
      - ./bin/mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: feedzy_wordpress
    privileged: true
    depends_on:
      - mysql
    image: hardeepasrani/pirate-brewery
    networks:
      - default
    ports:
      - 8888:80
    volumes:
       - ~/wpcore:/var/www/html/
       - ./wp-content:/var/www/html/wp-content/
       - .:/var/www/html/wp-content/plugins/feedzy-rss-feeds/
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_ROOT_PASSWORD: wordpress


