name: Release

on:
  push:
    branches:
      - master
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Release new version
        id: release
        run: |
          npm run release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: themeisle[bot]
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_ANNOUNCEMENTS }}
          SEMANTIC_RELEASE_PACKAGE: Feedzy(free)
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: themeisle[bot]
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
