name: Test e2e

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
jobs:
  e2e:
    name: E2E for ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
          env: ["default","gutenberg"]

    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: npm-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm deps
        run: npm ci
      - name: Install composer deps
        run: composer install --no-dev
      - name: Bootstrap environment
        run: docker-compose -f docker-compose.travis.yml up -d
      - name: Install environment
        run: |
          bash ./bin/wp-init.sh
          bash ./bin/run-e2e-tests-${{matrix.env}}.sh
      - name: Run ${{ matrix.env }} Cypress tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        uses: cypress-io/github-action@v2
        with:
          env: host=localhost,port=8080
          browser: chrome
          install: ${{ ! steps.npm-and-build-cache.outputs.cache-hit }}
          headless: true
          spec: cypress/integration/${{ matrix.env }}/**/*